"""
Django settings for credisystem project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path
from django.core.exceptions import ImproperlyConfigured
from decouple import AutoConfig

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
config = AutoConfig(search_path=BASE_DIR)

def env_bool(name, default=False):
    return config(name, default=default, cast=bool)


# --------------------------------------------------------------------------
# Claves y secretos: SIEMPRE desde variables de entorno, nunca hardcodeadas
# ni commiteadas a Git. Ver .env.example para las variables requeridas.
# --------------------------------------------------------------------------
SECRET_KEY = config("DJANGO_SECRET_KEY", default="django-insecure-local-development-only")
DEBUG = env_bool("DJANGO_DEBUG", True)
ALLOWED_HOSTS = [h.strip() for h in config("DJANGO_ALLOWED_HOSTS", default="localhost,127.0.0.1").split(",") if h.strip()]

if not DEBUG:
    if SECRET_KEY.startswith("django-insecure-") or len(SECRET_KEY) < 50:
        raise ImproperlyConfigured("DJANGO_SECRET_KEY debe ser una clave fuerte en producción.")
    if not ALLOWED_HOSTS:
        raise ImproperlyConfigured("DJANGO_ALLOWED_HOSTS debe configurarse en producción.")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Terceros
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',

    # Apps propias del proyecto
    'usuarios',
    'creditos',
    'frontend',
]

AUTH_USER_MODEL = 'usuarios.Usuario'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'credisystem.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'credisystem.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases
#
# MySQL en producción, usando SIEMPRE una clave/usuario de DB con
# privilegios acotados (nunca el usuario root). Credenciales por env.
# En desarrollo local sin MySQL configurado, cae a SQLite automáticamente.

if config("DB_ENGINE", default="") == "mysql":
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': config("DB_NAME"),
            'USER': config("DB_USER"),          # usuario de DB con permisos mínimos
            'PASSWORD': config("DB_PASSWORD"),
            'HOST': config("DB_HOST", default="localhost"),
            'PORT': config("DB_PORT", default="3306"),
            'OPTIONS': {
                'charset': 'utf8mb4',
                'ssl': {'ssl_mode': config("DB_SSL_MODE", default="PREFERRED")},
            },
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"
STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration
#
# En desarrollo, los correos (verificación de cuenta, recuperación de
# contraseña) se imprimen en la consola en vez de enviarse de verdad.
# En producción, configurar SMTP real (Gmail, SendGrid, etc.) por env.
if os.getenv("EMAIL_HOST"):
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_HOST = os.environ["EMAIL_HOST"]
    EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
    EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "True") == "True"
    EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
    EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
    DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", EMAIL_HOST_USER)
else:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"


# WhatsApp Cloud API
WHATSAPP_ACCESS_TOKEN = os.getenv("WHATSAPP_ACCESS_TOKEN", "")
WHATSAPP_PHONE_NUMBER_ID = os.getenv("WHATSAPP_PHONE_NUMBER_ID", "")
WHATSAPP_BUSINESS_ACCOUNT_ID = os.getenv("WHATSAPP_BUSINESS_ACCOUNT_ID", "")
WHATSAPP_API_VERSION = os.getenv("WHATSAPP_API_VERSION", "v25.0")
WHATSAPP_TEMPLATE_NAME = os.getenv("WHATSAPP_TEMPLATE_NAME", "")
WHATSAPP_TEMPLATE_LANGUAGE = os.getenv("WHATSAPP_TEMPLATE_LANGUAGE", "es_AR")
WHATSAPP_TEMPLATE_OTP_BUTTON = os.getenv("WHATSAPP_TEMPLATE_OTP_BUTTON", "False").lower() == "true"


# --------------------------------------------------------------------------
# Seguridad (checklist del proyecto). Estos flags quedan desactivados en
# DEBUG=True para no romper el desarrollo local sin HTTPS, y se activan
# solos apenas DEBUG=False en el .env de producción.
# --------------------------------------------------------------------------
DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

if not DEBUG:
    SECURE_SSL_REDIRECT = True                 # Fuerza HTTPS
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SESSION_COOKIE_SECURE = True                # Cookies solo por HTTPS
    CSRF_COOKIE_SECURE = True
    SECURE_CONTENT_TYPE_NOSNIFF = True          # Cabeceras de seguridad
    X_FRAME_OPTIONS = 'DENY'
    SECURE_REFERRER_POLICY = 'same-origin'
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_TRUSTED_ORIGINS = [o.strip() for o in config('DJANGO_CSRF_TRUSTED_ORIGINS', default='').split(',') if o.strip()]

# Framework REST. La autenticación real (JWT) se define cuando construyamos
# el módulo de auth; por ahora solo se deja la base preparada.
REST_FRAMEWORK = {
    'EXCEPTION_HANDLER': 'credisystem.errors.api_exception_handler',
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_THROTTLE_CLASSES': (
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ),
    'DEFAULT_THROTTLE_RATES': {
        'anon': '20/min',    # protección anti-bots / fuerza bruta básica
        'user': '100/min',
        'login': '10/min',   # limita intentos de login por IP
    },
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id_usuario',
    'USER_ID_CLAIM': 'user_id',
}

# --------------------------------------------------------------------------
# Reglas de negocio de autenticación (checklist de seguridad)
# --------------------------------------------------------------------------
AUTH_MAX_INTENTOS_FALLIDOS = 5      # límite de intentos de login
AUTH_VENTANA_INTENTOS_MIN = 15      # ventana en minutos para contar intentos
AUTH_BLOQUEO_MINUTOS = 15           # duración del bloqueo temporal
AUTH_CODIGO_EXPIRA_MINUTOS = 10     # vencimiento de códigos de verificación

# --------------------------------------------------------------------------
# Reglas de negocio de créditos (CU4 y CU8)
# --------------------------------------------------------------------------
CREDITO_MONTO_MINIMO = 10000
CREDITO_MONTO_MAXIMO = 3000000
CREDITO_PLAZO_MINIMO_MESES = 1
CREDITO_PLAZO_MAXIMO_MESES = 60
CREDITO_TASA_INTERES_ANUAL = "85.00"  # tasa fija simplificada para el proyecto académico
CREDITO_PORCENTAJE_MAX_INGRESOS = "0.30"  # la cuota no puede superar el 30% del ingreso declarado

# Subida de archivos (comprobantes de ingresos) - restringida por tipo y tamaño
SOLICITUD_EXTENSIONES_PERMITIDAS = [".pdf", ".jpg", ".jpeg", ".png"]
SOLICITUD_ARCHIVO_MAX_MB = 5

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# --------------------------------------------------------------------------
# Mercado Pago (CU5). El access token es secreto: sale del .env, nunca
# se hardcodea ni se commitea. El webhook secret se usa para validar la
# firma de las notificaciones entrantes (evita que cualquiera pueda
# pegarle a ese endpoint simulando pagos aprobados).
# --------------------------------------------------------------------------
MERCADOPAGO_ACCESS_TOKEN = os.getenv("MERCADOPAGO_ACCESS_TOKEN", "")
MERCADOPAGO_WEBHOOK_SECRET = os.getenv("MERCADOPAGO_WEBHOOK_SECRET", "")
# URL pública del backend, para armar back_urls y el notification_url que
# Mercado Pago necesita (debe ser accesible desde internet, no localhost).
BACKEND_PUBLIC_URL = config("BACKEND_PUBLIC_URL", default="http://localhost:8000")

# --------------------------------------------------------------------------
# Notificaciones push (CU7) vía Firebase Cloud Messaging. Si no se
# configura la ruta al credentials.json, el envío se degrada a un
# no-op (queda solo el registro en la tabla Notificacion).
# --------------------------------------------------------------------------
FCM_CREDENTIALS_PATH = os.getenv("FCM_CREDENTIALS_PATH", "")
