# Generated by Django 6.1 on 2026-08-21 23:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoVerificacion',
            fields=[
                ('id_codigo', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=6)),
                ('tipo', models.CharField(choices=[('registro', 'Verificación de registro'), ('recuperacion', 'Recuperación de contraseña')], max_length=20)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('expira', models.DateTimeField()),
                ('usado', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigos_verificacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'codigo_verificacion',
                'indexes': [models.Index(fields=['usuario', 'tipo', 'usado'], name='codigo_veri_usuario_699849_idx')],
            },
        ),
    ]
