# Generated by Django 6.1 on 2026-08-22 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_codigoverificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='notificaciones_push_activas',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='push_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
