# Generated by Django 5.2.17 on 2026-10-05 14:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PreguntaFrecuente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=180)),
                ('respuesta', models.TextField(help_text='Texto público. No incluir datos personales ni HTML.', max_length=2000)),
                ('destino', models.CharField(blank=True, choices=[('', 'Sin enlace'), ('registro', 'Crear cuenta'), ('solicitud', 'Solicitar crédito (iniciar sesión)'), ('solicitudes', 'Mis solicitudes (iniciar sesión)'), ('cuotas', 'Estado de cuenta (iniciar sesión)'), ('recuperar', 'Recuperar contraseña')], default='', max_length=20)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'pregunta frecuente',
                'verbose_name_plural': 'preguntas frecuentes',
                'ordering': ['orden', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionAsistente',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('activo', models.BooleanField(default=True)),
                ('numero_whatsapp', models.CharField(blank=True, help_text='Número público de atención, en formato internacional. Vacío: no aparece el botón de WhatsApp.', max_length=15, validators=[django.core.validators.RegexValidator('\\A[1-9][0-9]{7,14}\\Z', 'Usá entre 8 y 15 dígitos, con código de país, sin +, espacios ni guiones.')], verbose_name='número de WhatsApp')),
            ],
            options={
                'verbose_name': 'configuración del asistente',
                'verbose_name_plural': 'configuración del asistente',
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='asistente_config_unica')],
            },
        ),
    ]
