# Generated by Django 6.1 on 2026-08-21 22:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloqueoCuenta',
            fields=[
                ('id_bloqueo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('motivo', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'bloqueo_cuenta',
            },
        ),
        migrations.CreateModel(
            name='Credito',
            fields=[
                ('id_credito', models.AutoField(primary_key=True, serialize=False)),
                ('monto_original', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('tasa_interes_anual', models.DecimalField(decimal_places=2, max_digits=5)),
                ('plazo_meses', models.PositiveIntegerField()),
                ('fecha_otorgamiento', models.DateField()),
                ('primer_vencimiento', models.DateField()),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('cancelado', 'Cancelado'), ('en_mora', 'En mora')], default='activo', max_length=20)),
            ],
            options={
                'db_table': 'credito',
            },
        ),
        migrations.CreateModel(
            name='IntentoAcceso',
            fields=[
                ('id_intento', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_intento', models.DateTimeField(auto_now_add=True)),
                ('exito', models.BooleanField()),
                ('ip', models.GenericIPAddressField()),
                ('motivo_fallo', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'intento_acceso',
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id_notificacion', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('vencimiento', 'Vencimiento'), ('promocion', 'Promoción'), ('estado_solicitud', 'Estado de solicitud')], max_length=30)),
                ('mensaje', models.CharField(max_length=255)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('leida', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'notificacion',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('medio_pago', models.CharField(choices=[('debito', 'Débito'), ('credito', 'Crédito'), ('efectivo', 'Efectivo'), ('billetera', 'Billetera virtual')], max_length=20)),
                ('comprobante_url', models.CharField(blank=True, max_length=255, null=True)),
                ('resultado', models.CharField(choices=[('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], max_length=20)),
            ],
            options={
                'db_table': 'pago',
            },
        ),
        migrations.CreateModel(
            name='Simulacion',
            fields=[
                ('id_simulacion', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('plazo_meses', models.PositiveIntegerField()),
                ('tasa_anual', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cuota_estim', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'simulacion',
            },
        ),
        migrations.CreateModel(
            name='SolicitudCredito',
            fields=[
                ('id_solicitud', models.AutoField(primary_key=True, serialize=False)),
                ('monto_solicitado', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('plazo_meses', models.PositiveIntegerField()),
                ('ingresos_mensuales', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('estado', models.CharField(choices=[('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('en_revision', 'En revisión')], default='en_revision', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('motivo_rechazo', models.CharField(blank=True, max_length=255, null=True)),
                ('comprobantes_url', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'solicitud_credito',
            },
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id_transaccion', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('pago', 'Pago'), ('solicitud', 'Solicitud'), ('desembolso', 'Desembolso'), ('simulacion', 'Simulación')], max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('importe', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
            options={
                'db_table': 'transaccion',
            },
        ),
    ]
