# Generated by Django 6.1 on 2026-08-21 22:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('creditos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bloqueocuenta',
            name='id_usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='bloqueos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='credito',
            name='id_usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.PROTECT, related_name='creditos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='intentoacceso',
            name='id_usuario',
            field=models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intentos_acceso', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='id_usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pago',
            name='id_credito',
            field=models.ForeignKey(db_column='id_credito', on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='creditos.credito'),
        ),
        migrations.AddField(
            model_name='simulacion',
            name='id_usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='simulaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitudcredito',
            name='id_usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='id_usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.PROTECT, related_name='transacciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='bloqueocuenta',
            index=models.Index(fields=['id_usuario', 'fecha_fin'], name='bloqueo_cue_id_usua_bb219b_idx'),
        ),
        migrations.AddIndex(
            model_name='credito',
            index=models.Index(fields=['id_usuario', 'estado'], name='credito_id_usua_c8f3d5_idx'),
        ),
        migrations.AddIndex(
            model_name='intentoacceso',
            index=models.Index(fields=['id_usuario', 'fecha_intento'], name='intento_acc_id_usua_a052bf_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(fields=['id_usuario', 'leida'], name='notificacio_id_usua_da5fc9_idx'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['id_credito', 'fecha_pago'], name='pago_id_cred_0226c4_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudcredito',
            index=models.Index(fields=['id_usuario', 'estado'], name='solicitud_c_id_usua_157fbe_idx'),
        ),
        migrations.AddIndex(
            model_name='transaccion',
            index=models.Index(fields=['id_usuario', 'fecha'], name='transaccion_id_usua_7da590_idx'),
        ),
    ]
