# Generated by Django 6.1 on 2026-08-22 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='external_reference',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='mp_payment_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='mp_preference_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='medio_pago',
            field=models.CharField(blank=True, choices=[('debito', 'Débito'), ('credito', 'Crédito'), ('efectivo', 'Efectivo'), ('billetera', 'Billetera virtual')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='resultado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20),
        ),
    ]
