# Generated by Django 5.2.17 on 2026-09-20 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0006_cuota'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='cuota',
            new_name='cuota_credito_8fc444_idx',
            old_name='cuota_cred_est_venc_idx',
        ),
        migrations.RenameIndex(
            model_name='historialsolicitud',
            new_name='historial_s_solicit_1dfa76_idx',
            old_name='historial_s_solicit_72c8db_idx',
        ),
    ]
