# Generated by Django 5.2.17 on 2026-09-20 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0007_registro_pagos_cuotas'),
        ('creditos', '0007_rename_cuota_cred_est_venc_idx_cuota_credito_8fc444_idx_and_more'),
    ]

    operations = [
    ]
