# Generated by Django 5.2.17 on 2026-10-03 00:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0008_merge_20260920_2018'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcredito',
            name='autorizacion_consulta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solicitudcredito',
            name='bcra_estado',
            field=models.CharField(default='no_consultado', editable=False, max_length=20),
        ),
        migrations.AddField(
            model_name='solicitudcredito',
            name='bcra_fecha',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='solicitudcredito',
            name='bcra_informe',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='solicitudcredito',
            name='cuil_cuit',
            field=models.CharField(blank=True, default='', max_length=11),
        ),
        migrations.AddField(
            model_name='solicitudcredito',
            name='id_envio',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddConstraint(
            model_name='solicitudcredito',
            constraint=models.UniqueConstraint(fields=('id_usuario', 'id_envio'), name='uq_solicitud_usuario_envio'),
        ),
    ]
